/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as PoetryIndexRouteImport } from './routes/poetry/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as PoetryPoetryIdRouteImport } from './routes/poetry/$poetryId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoetryIndexRoute = PoetryIndexRouteImport.update({
  id: '/poetry/',
  path: '/poetry/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const PoetryPoetryIdRoute = PoetryPoetryIdRouteImport.update({
  id: '/poetry/$poetryId',
  path: '/poetry/$poetryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/poetry/$poetryId': typeof PoetryPoetryIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/poetry/': typeof PoetryIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/poetry/$poetryId': typeof PoetryPoetryIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/poetry': typeof PoetryIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/poetry/$poetryId': typeof PoetryPoetryIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/poetry/': typeof PoetryIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/poetry/$poetryId'
    | '/projects/$projectId'
    | '/poetry/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/poetry/$poetryId'
    | '/projects/$projectId'
    | '/poetry'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/poetry/$poetryId'
    | '/projects/$projectId'
    | '/poetry/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PoetryPoetryIdRoute: typeof PoetryPoetryIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  PoetryIndexRoute: typeof PoetryIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poetry/': {
      id: '/poetry/'
      path: '/poetry'
      fullPath: '/poetry/'
      preLoaderRoute: typeof PoetryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poetry/$poetryId': {
      id: '/poetry/$poetryId'
      path: '/poetry/$poetryId'
      fullPath: '/poetry/$poetryId'
      preLoaderRoute: typeof PoetryPoetryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PoetryPoetryIdRoute: PoetryPoetryIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  PoetryIndexRoute: PoetryIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
